{{-  $imageTag := printf "%s:%s" .Values.fastapi.image_repo .Values.fastapi.image_version -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  labels:
    app: products
    tier: restapi
spec:
  replicas: {{ .Values.autoscaling.minReplicas }}
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: products
      tier: restapi
  template:
    metadata:
      name: fastapi
      labels:
        app: products
        tier: restapi
    spec:
      containers:
      - name: fastapi
        image: {{ $imageTag | quote }} 
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: '0.025'
          requests:
            cpu: '0.008'
        env:
        - name: DB_HOST
          value: {{ .Values.mongodb.db_host | quote}}
        - name: DB_PORT
          value: {{ .Values.mongodb.db_port | quote }}
        - name: DB_NAME
          value: {{ .Values.mongodb.db_name | quote }} 
        - name: DB_USER
          value: {{ .Values.mongodb.db_user | quote }}
        - name: DB_PASSWD
          value: {{ .Values.mongodb.db_pass | quote }} 
        ports:
          - containerPort: {{ .Values.fastapi.container_port }}