apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.db_host }}
  labels:
    app: products
    tier: database
spec:
  ports:
    - port: {{ .Values.mongodb.db_port }}
  selector:
    app: products
    tier: database
