apiVersion: v1
kind: Service
metadata:
  name: fastapi-svc
  labels:
    app: products
    tier: restapi
spec:
  ports:
  - nodePort: 32132
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: products
    tier: restapi
  type: NodePort