apiVersion: v1
kind: Service
metadata:
  name: fastapi-svc
  labels:
    app: products
    tier: restapi
spec:
  ports:
  - nodePort: {{ .Values.fastapi.node_port }}
    port: {{ .Values.fastapi.container_port }}
    protocol: TCP
    targetPort: {{ .Values.fastapi.container_port }}
  selector:
    app: products
    tier: restapi
  type: NodePort